# Vespara - Strict Dart/Flutter Analysis Options
# This configuration helps minimize excess code and enforce best practices

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Treat these as errors (will block builds)
    unused_import: error
    unused_local_variable: error
    dead_code: error
    # Treat these as warnings
    unused_element: warning
    unused_field: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # === REMOVE UNNECESSARY CODE ===
    - unnecessary_this
    - unnecessary_new
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_getters_setters
    - unnecessary_statements
    - unnecessary_brace_in_string_interps
    - unnecessary_await_in_return
    - unnecessary_late
    - unnecessary_to_list_in_spreads
    
    # === PREFER SIMPLER/SHORTER CODE ===
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_single_quotes
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - prefer_null_aware_method_calls
    - prefer_conditional_assignment
    - prefer_spread_collections
    - prefer_collection_literals
    - prefer_for_elements_to_map_fromIterable
    - prefer_iterable_whereType
    - prefer_contains
    - prefer_interpolation_to_compose_strings
    - prefer_adjacent_string_concatenation
    - prefer_function_declarations_over_variables
    - prefer_expression_function_bodies
    - prefer_if_elements_to_conditional_expressions
    - prefer_inlined_adds
    
    # === AVOID BLOATED CODE ===
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - avoid_returning_null_for_void
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_types_on_closure_parameters
    - avoid_renaming_method_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_multiple_declarations_per_line
    
    # === FLUTTER-SPECIFIC OPTIMIZATIONS ===
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - use_colored_box
    - use_decorated_box
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - require_trailing_commas
    
    # === CODE ORGANIZATION ===
    - directives_ordering
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    
    # === SAFETY & RELIABILITY ===
    - always_declare_return_types
    # Note: always_require_non_null_named_parameters removed in Dart 3.3 (now enforced by null safety)
    - annotate_overrides
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - exhaustive_cases
    - no_duplicate_case_values
    - null_closures
    - prefer_typing_uninitialized_variables
    - type_annotate_public_apis
    - unawaited_futures
    - valid_regexps

# DCM Configuration for advanced code metrics
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 5
    maximum-nesting-level: 5
    lines-of-code: 100
    number-of-methods: 15
    weight-of-class: 0.33
    source-lines-of-code: 50
  
  rules:
    # Avoid long functions
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - avoid-long-functions:
        max-length: 50
    - avoid-long-parameter-list:
        max-amount: 5
    
    # Simplify code
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - prefer-immediate-return
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 2
    
    # Flutter optimizations
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - use-setstate-synchronously
